before_install:
  - git config --global user.name travis
  - git config --global user.email travis@locahost
  - npm install npm@5 -g
language: node_js
script:
  - npm install lcov-server -g
  - npm run lint
  - npm run coverage
  - cat coverage/lcov.info | lcov-server --upload https://lcov-server.gabrielcsapo.com
node_js:
  - "6"
  - "8"
os:
  - linux
sudo: false
